name: Build

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Lazarus
      run: |
        # Install Lazarus 2.2.2
        choco install lazarus --version=2.2.2 - y
        # Install cross-compilation add-on
        choco install fpc-src -y
        choco install fpc -y

    - name: Build with Lazarus
      run: |
        # Commands to build with Lazarus on Windows
        lazbuild cheatengine.lpi

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CheatEngine-build
        path: |
          CheatEngine/bin
          CheatEngine/CheatEngine/bin
